project:
  type: website

website:
  title: "SMT201-GISProject"
  navbar:
    left:
      - text: Overview
        href: "Overview.html"
      - text: Methodology
        href: ""
      - text: Results and Discussion
        href: ""
      - text: Interactive map
        href: "qgis2web/index.html"
    right:
      - href: index.qmd
        text: Home
      - text: Team
        href: about.qmd
format:
  html:
    theme:
      - united
      - brand
    css: styles.css
    toc: true

editor: visual

